"""empty message

Revision ID: 55a5ccc499f2
Revises: 26d0ec39dc3e
Create Date: 2016-04-12 11:22:55.296195

"""

# revision identifiers, used by Alembic.
revision = '55a5ccc499f2'
down_revision = '26d0ec39dc3e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
